-- CreateEnum
CREATE TYPE "ApplicationStatus" AS ENUM ('submitted', 'under_review', 'approved', 'rejected');

-- CreateTable
CREATE TABLE "applications" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "status" "ApplicationStatus" NOT NULL DEFAULT 'submitted',
    "fullName" TEXT NOT NULL,
    "dob" TEXT,
    "gender" TEXT,
    "mobile" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "address" TEXT,
    "district" TEXT,
    "institution" TEXT,
    "qualification" TEXT,
    "fatherName" TEXT,
    "fatherOccupation" TEXT,
    "fatherContact" TEXT,
    "motherName" TEXT,
    "motherOccupation" TEXT,
    "motherContact" TEXT,
    "guardianName" TEXT,
    "guardianRelation" TEXT,
    "guardianContact" TEXT,
    "parentStatus" TEXT,
    "bothParentsDeceased" TEXT,
    "fatherDeathCertUrl" TEXT,
    "motherDeathCertUrl" TEXT,
    "singleParent" TEXT,
    "supportingParent" TEXT,
    "supportingDocumentUrl" TEXT,
    "annualIncome" TEXT,
    "incomeCertificateUrl" TEXT,
    "expenseBearer" TEXT,
    "selfEarning" TEXT,
    "employmentType" TEXT,
    "monthlyIncome" TEXT,
    "selfIncomeDocUrl" TEXT,
    "supportsDependents" TEXT,
    "numDependents" TEXT,
    "socialCategory" TEXT,
    "communityCertificateUrl" TEXT,
    "existingScholarship" TEXT,
    "scholarshipName" TEXT,
    "scholarshipProvider" TEXT,
    "scholarshipAmount" TEXT,
    "scholarshipYear" TEXT,
    "scholarshipDocUrl" TEXT,
    "tenth" JSONB,
    "twelfth" JSONB,
    "college" JSONB,
    "govtSchoolEvidenceUrl" TEXT,
    "hasDiploma" TEXT,
    "diplomaPercentage" TEXT,
    "diplomaMarkSheetUrl" TEXT,
    "latestAcademicPercentage" TEXT,
    "medium" TEXT,
    "tamilMediumTill12" TEXT,
    "tamilMediumEvidenceUrl" TEXT,
    "examCategory" TEXT,
    "examName" TEXT,
    "examYear" TEXT,
    "targetAttempt" TEXT,
    "relevantQualification" TEXT,
    "coachingMode" TEXT,
    "studentPhotoUrl" TEXT,
    "identityDocumentUrl" TEXT,
    "educationalCertificatesUrl" TEXT,
    "declarationAccepted" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "applications_pkey" PRIMARY KEY ("id")
);
